language: csharp
solution: all_code/FlexibleParser.sln
notifications:
  email: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libxml-checker-perl libdbd-pg-perl libperl-critic-perl libdevel-cover-perl
