using System;
using System.Collections.Generic;

namespace FlexibleParser
{
    public enum TimeZoneIANAEnum
    {
        None = 0,

        Africa_Abidjan, Africa_Algiers, Africa_Cairo, Africa_El_Aaiun,
        Africa_Ceuta, Africa_Lagos, Africa_Accra, Africa_Bissau,
        Africa_Nairobi, Africa_Monrovia, Africa_Tripoli, Africa_Casablanca,
        Africa_Maputo, Africa_Windhoek, Africa_Khartoum, Africa_Ndjamena,
        Africa_Tunis, Africa_Johannesburg, Africa_Ouagadougou, Africa_Banjul,
        Africa_Conakry, Africa_Bamako, Africa_Nouakchott, Atlantic_St_Helena,
        Africa_Freetown, Africa_Dakar, Africa_Sao_Tome, Africa_Lome, Africa_Luanda,
        Africa_Porto_Novo, Africa_Kinshasa, Africa_Bangui, Africa_Brazzaville,
        Africa_Douala, Africa_Libreville, Africa_Malabo, Africa_Niamey,
        Africa_Bujumbura, Africa_Gaborone, Africa_Lubumbashi, Africa_Maseru,
        Africa_Blantyre, Africa_Kigali, Africa_Mbabane, Africa_Lusaka,
        Africa_Harare, Africa_Djibouti, Africa_Asmera, Africa_Addis_Ababa,
        Africa_Mogadishu, Africa_Juba, Africa_Dar_Es_Salaam, Africa_Kampala,

        America_Argentina_Buenos_Aires, America_Argentina_Cordoba,
        America_Argentina_Salta, America_Argentina_Jujuy,
        America_Argentina_Tucuman, America_Argentina_Catamarca,
        America_Argentina_La_Rioja, America_Argentina_San_Juan,
        America_Argentina_Mendoza, America_Argentina_San_Luis,
        America_Argentina_Rio_Gallegos, America_Argentina_Ushuaia,
        America_Barbados, America_La_Paz, America_Kralendijk,
        America_Noronha, America_Dominica, America_Grenada,
        America_Guadeloupe, America_St_Kitts, America_St_Lucia,
        America_Belem, America_Fortaleza, America_Recife,
        America_Araguaina, America_Maceio, America_Bahia,
        America_Sao_Paulo, America_Campo_Grande, America_Cuiaba,
        America_Santarem, America_Porto_Velho, America_Boa_Vista,
        America_Manaus, America_Eirunepe, America_Rio_Branco,
        America_Nassau, America_Belize, America_St_Johns,
        America_Halifax, America_Glace_Bay, America_Moncton,
        America_Goose_Bay, America_Blanc_Sablon,
        America_Toronto, America_Nipigon, America_Thunder_Bay,
        America_Iqaluit, America_Pangnirtung, 
        America_Winnipeg, America_Rainy_River, America_Resolute,
        America_Rankin_Inlet, America_Regina, America_Swift_Current,
        America_Edmonton, America_Cambridge_Bay, America_Yellowknife,
        America_Inuvik, America_Creston, America_Dawson_Creek,
        America_Fort_Nelson, America_Vancouver, America_Whitehorse,
        America_Dawson, America_Santiago, America_Punta_Arenas,
        America_Bogota, America_Costa_Rica, America_Havana,
        America_Curacao, America_Santo_Domingo, America_Guayaquil,
        America_Cayenne, America_Godthab, America_Danmarkshavn,
        America_Scoresbysund, America_Thule, America_Guatemala,
        America_Guyana, America_Tegucigalpa, America_Port_au_Prince,
        America_Jamaica, America_Martinique, America_Montserrat,
        America_Mexico_City,
        America_Cancun, America_Merida, America_Monterrey,
        America_Matamoros, America_Mazatlan, America_Chihuahua,
        America_Ojinaga, America_Hermosillo, America_Tijuana,
        America_Bahia_Banderas, America_Managua, America_Panama,
        America_Port_of_Spain, America_St_Vincent, America_Tortola,
        America_St_Thomas, America_New_York, America_Detroit,
        America_Kentucky_Monticello,
        America_Indiana_Indianapolis, America_Indiana_Vincennes,
        America_Indiana_Winamac, America_Indiana_Marengo,
        America_Indiana_Petersburg, America_Indiana_Vevay,
        America_Chicago, America_Indiana_Tell_City,
        America_Indiana_Knox, America_Menominee, America_North_Dakota_Center,
        America_North_Dakota_New_Salem, America_North_Dakota_Beulah,
        America_Denver, America_Boise, America_Phoenix, America_Los_Angeles,
        America_Anchorage, America_Juneau, America_Sitka, America_Metlakatla,
        America_Yakutat, America_Nome, America_Adak, America_Montevideo,
        America_Caracas, America_Lima, America_Miquelon, America_Puerto_Rico,
        America_Asuncion, America_Paramaribo, America_El_Salvador,
        America_Grand_Turk, America_Santa_Isabel, America_Coral_Harbour,
        America_Cayman, America_Montreal, America_Louisville,
        America_Antigua, America_Aruba, America_St_Barthelemy,

        Antarctica_Casey, Antarctica_Davis, Antarctica_DumontDUrville,
        Antarctica_Mawson, Antarctica_Palmer, Antarctica_Rothera,
        Antarctica_Syowa, Antarctica_Vostok, Antarctica_Macquarie, 
        Antarctica_McMurdo,

        Asia_Dubai, Asia_Kabul, Asia_Yerevan, Asia_Dhaka, Asia_Brunei,
        Asia_Thimphu, Asia_Shanghai, Asia_Urumqi, Asia_Nicosia,
        Asia_Famagusta, Asia_Tbilisi, Asia_Hong_Kong, Asia_Jakarta,
        Asia_Pontianak, Asia_Makassar, Asia_Jayapura, Asia_Pyongyang,
        Asia_Seoul, Asia_Almaty, Asia_Qyzylorda, Asia_Aqtobe, Asia_Aqtau,
        Asia_Atyrau, Asia_Oral, Asia_Beirut, Asia_Colombo, Asia_Jerusalem,
        Asia_Baghdad, Asia_Tehran, Asia_Amman, Asia_Tokyo,
        Asia_Bishkek, Asia_Ulaanbaatar, Asia_Hovd,
        Asia_Choibalsan, Asia_Macau, Asia_Kuala_Lumpur, Asia_Kuching,
        Asia_Kathmandu, Asia_Manila, Asia_Karachi, Asia_Gaza, Asia_Hebron,
        Asia_Qatar, Asia_Yekaterinburg, Asia_Omsk, Asia_Novosibirsk,
        Asia_Barnaul, Asia_Tomsk, Asia_Novokuznetsk, Asia_Krasnoyarsk,
        Asia_Irkutsk, Asia_Chita, Asia_Yakutsk, Asia_Khandyga,
        Asia_Vladivostok, Asia_Ust_Nera, Asia_Magadan, Asia_Sakhalin,
        Asia_Srednekolymsk, Asia_Kamchatka, Asia_Anadyr, Asia_Riyadh,
        Asia_Singapore, Asia_Damascus, Asia_Samarkand,
        Asia_Dili, Asia_Ashgabat, Asia_Tashkent, Asia_Bangkok,
        Asia_Dushanbe, Asia_Taipei, Asia_Baku, Asia_Bahrain, Asia_Kuwait,
        Asia_Aden, Asia_Muscat, Asia_Ekaterinburg, Asia_Calcutta,
        Asia_Rangoon, Asia_Phnom_Penh, Asia_Saigon, Asia_Vientiane,

        Atlantic_Bermuda, Atlantic_Cape_Verde, Atlantic_Stanley, Atlantic_Canary,
        Atlantic_South_Georgia, Atlantic_Reykjavik, Atlantic_Madeira,
        Atlantic_Azores, Atlantic_Faeroe,

        Australia_Lord_Howe, Australia_Hobart, Australia_Currie,
        Australia_Melbourne, Australia_Sydney, Australia_Broken_Hill,
        Australia_Brisbane, Australia_Lindeman, Australia_Adelaide,
        Australia_Darwin, Australia_Perth, Australia_Eucla,

        Etc_GMT, Etc_GMT_Plus_1, Etc_GMT_Plus_10, Etc_GMT_Plus_11, Etc_GMT_Plus_12,
        Etc_GMT_Plus_2, Etc_GMT_Plus_3, Etc_GMT_Plus_4, Etc_GMT_Plus_5, Etc_GMT_Plus_6,
        Etc_GMT_Plus_7, Etc_GMT_Plus_8, Etc_GMT_Plus_9, Etc_GMT_Minus_1, Etc_GMT_Minus_10,
        Etc_GMT_Minus_11, Etc_GMT_Minus_12, Etc_GMT_Minus_13, Etc_GMT_Minus_14,
        Etc_GMT_Minus_2, Etc_GMT_Minus_3, Etc_GMT_Minus_4, Etc_GMT_Minus_5, Etc_GMT_Minus_6,
        Etc_GMT_Minus_7, Etc_GMT_Minus_8, Etc_GMT_Minus_9, Etc_Greenwich,
        Etc_Universal, Etc_UTC, MST7MDT, PST8PDT,

        Europe_Andorra, Europe_Tirane, Europe_Vienna, Europe_Brussels,
        Europe_Sofia, Europe_Minsk, Europe_Zurich, Europe_Prague,
        Europe_Berlin, Europe_Copenhagen, Europe_Tallinn, Europe_Madrid,
        Europe_Paris, Europe_London, Europe_Helsinki, Europe_Gibraltar,
        Europe_Athens, Europe_Budapest, Europe_Dublin, Europe_Rome,
        Europe_Vilnius, Europe_Luxembourg, Europe_Riga, Europe_Monaco,
        Europe_Chisinau, Europe_Malta, Europe_Amsterdam, Europe_Oslo,
        Europe_Warsaw, Europe_Lisbon, Europe_Bucharest, Europe_Belgrade,
        Europe_Kaliningrad, Europe_Moscow, Europe_Simferopol,
        Europe_Volgograd, Europe_Kirov, Europe_Astrakhan, Europe_Saratov,
        Europe_Ulyanovsk, Europe_Samara, Europe_Stockholm, Europe_Istanbul,
        Europe_Kiev, Europe_Uzhgorod, Europe_Zaporozhye, Europe_Guernsey,
        Europe_Isle_Of_Man, Europe_Jersey, Europe_Vaduz, Europe_Busingen,
        Europe_Longyearbyen, Europe_San_Marino, Europe_Vatican,
        Europe_Podgorica, Europe_Ljubljana, Europe_Bratislava,
        Europe_Sarajevo, Europe_Zagreb, Europe_Skopje, Europe_Mariehamn,

        Indian_Cocos, Indian_Christmas, Indian_Chagos, Indian_Mauritius,
        Indian_Maldives, Indian_Reunion, Indian_Mahe, Indian_Kerguelen,
        Indian_Comoro, Indian_Antananarivo, Indian_Mayotte,

        Pacific_Pago_Pago, Pacific_Rarotonga, Pacific_Easter, Pacific_Galapagos,
        Pacific_Fiji, Pacific_Kosrae,
        Pacific_Guam, Pacific_Noumea, Pacific_Norfolk, Pacific_Tarawa,
        Pacific_Enderbury, Pacific_Kiritimati, Pacific_Majuro, Pacific_Kwajalein,
        Pacific_Nauru, Pacific_Niue, Pacific_Auckland, Pacific_Chatham,
        Pacific_Tahiti, Pacific_Marquesas, Pacific_Gambier, Pacific_Port_Moresby,
        Pacific_Bougainville, Pacific_Pitcairn, Pacific_Palau, Pacific_Guadalcanal,
        Pacific_Funafuti, Pacific_Fakaofo, Pacific_Tongatapu, Pacific_Wake,
        Pacific_Efate, Pacific_Honolulu, Pacific_Wallis, Pacific_Apia,
        Pacific_Midway, Pacific_Johnston, America_Marigot, America_Lower_Princes,
        Pacific_Truk, Pacific_Saipan, Pacific_Ponape
    }
}
